--- # a playbook for installing docker

- name: install docker and load some containers
	hosts: feste
	remote_user: ubuntu
	roles:
		- angstwad.docker_ubuntu
	tasks:
		- name: install the ubuntu docker image
			shell: docker pull ubuntu
			sudo: yes