--- # get base environment setup

- name: setup nodes for production-style work
  hosts: feste
  remote_user: ubuntu

  tasks:
    - name: ensure git
      yum: name=git state=present
      sudo: yes

    - name: get our repo
      git: 
        repo: git@github.com:michaelMinar/kafkaTweets.git
        dest: /home/ec2-user/git
        version: master
        update: yes

    - name: curl
      yum: name=curl state=present
      sudo: yes


    # - name: bash_profile
    #   copy: src=
