--- # get base environment setup

- name: setup nodes for production-style work
  hosts: feste
  remote_user: ubuntu

  tasks:
    # - name: ensure git
    #   apt: name=git state=present
    #   sudo: yes 

    
