# demo_setup.yml

- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    ami_id: ami-e7527ed7
    key_pair: mminarPersonal
    # -- list variables to generate security rules in local action below
    cidrs: [0.0.0.0/0]
    ports: [22, 80]

  tasks:
    - name: create rules groups
      local_action:
        module: template src=securityRules.j2 dest=./rules.yml

    - name: load vars
      include_vars: rules.yml

    - name: Provision a set of instances
      ec2:
        region: 'us-west-2'
        key_name: "{{ key_pair }}"
        group: twelfthNight
        instance_type: t2.micro
        image: "{{ ami_id }}"
        wait: true
        spot_price: 0.25
        exact_count: 1
        rules: "{{ security_rules }}"
        count_tag:
          Name: feste
        instance_tags:
          Name: feste
      register: ec2