# demo_setup.yml

- hosts: localhost # -- can't use 'localhost' as keyword once rules are in place
  connection: local
  vars:
    ami_id: ami-e7527ed7 # -- standard Amazon linux box
    # -- note this amazon linux box comes with: python, pip, java
    # ami_id: ami-29ebb519 # -- unbuntu server 
    key_pair: mminarPersonal
    # -- list variables to generate security rules in local action below
    cidrs: [0.0.0.0/0]
    ports: [22, 8080]

  tasks:
    - name: create rules groups
      local_action:
        module: template src=securityRules.j2 dest=./rules.yml
    - name: load vars
      include_vars: rules.yml

    - name: Provision a security group
      ec2_group:
        region: 'us-west-2'
        description: 'a security group for kafka tweets'
        name: 'twelfthNight'
        rules: "{{ security_rules }}"
        rules_egress:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0

    - name: Provision a set of instances
      ec2:
        region: 'us-west-2'
        key_name: "{{ key_pair }}"
        group: twelfthNight
        #instance_type: c4.xlarge
        instance_type: t2.micro
        image: "{{ ami_id }}"
        wait: true
        #spot_price: 0.2
        exact_count: 1
        count_tag:
          Name: feste
        instance_tags:
          Name: feste
      register: feste

    - name: create list of instances
      local_action:
        module: template src=hltemp dest=./instance.list

