# demo_setup.yml

- hosts: localhost # -- can't use 'localhost' as keyword once rules are in place
  connection: local
  gather_facts: False
  vars:
    # ami_id: ami-e7527ed7 # -- standard Amazon linux box
    ami_id: ami-29ebb519 # -- unbuntu server 
    key_pair: mminarPersonal
    # -- list variables to generate security rules in local action below
    cidrs: [0.0.0.0/0]
    ports: [22, 80]

  tasks:
    - name: create rules groups
      local_action:
        module: template src=securityRules.j2 dest=./rules.yml
    - name: load vars
      include_vars: rules.yml

    - name: Provision a security group
      ec2_group:
        region: 'us-west-2'
        description: 'a security group for kafka tweets'
        name: 'twelfthNight'
        rules: "{{ security_rules }}"

    - name: Provision a set of instances
      ec2:
        region: 'us-west-2'
        key_name: "{{ key_pair }}"
        group: twelfthNight
        instance_type: t2.micro
        image: "{{ ami_id }}"
        wait: true
        exact_count: 1
        count_tag:
          Name: feste
        instance_tags:
          Name: feste
      register: feste

